# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-04 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_readers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Feed',
        ),
    ]
